<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Content Condition="'$(IncludeModels)' != 'false'" Include="models\**\*.*;models-cunet\**\*.*;models-srmd\**\*.*;models-upconv_7_anime_style_art_rgb\**\*.*;models-upconv_7_photo\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </Content>
    </ItemGroup>
    <ItemGroup>
        <None Update="lucifer_ncnn_vulkan.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </None>
        <None Update="lucifer_ncnn_vulkan.lib">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>
        <None Update="lucifer_ncnn_vulkan.exp">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>
    </ItemGroup>

</Project>
