<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
        <AvaloniaCompileEnable>true</AvaloniaCompileEnable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(RuntimeIdentifier)' != ''">
        <PublishSingleFile>true</PublishSingleFile>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
        <PublishTrimmed>false</PublishTrimmed>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Desktop"/>
        <PackageReference Include="Avalonia.Themes.Fluent"/>
        <PackageReference Include="DiskInfoToolkit"/>
        <PackageReference Include="HarfBuzzSharp"/>
        <PackageReference Include="LibreHardwareMonitorLib"/>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="SkiaSharp"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <PackageReference Include="Tmds.DBus.Protocol"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\X.SuperResolution.Engine\X.SuperResolution.Engine.csproj"/>
    </ItemGroup>
</Project>
